[versions]
application-version = "0.0.1"
application-group = "ru.astrainteractive.kspreproducer"
kotlin-version = "2.1.0" # 1.9.21 is absolutely fine
[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-version" }
